travis:
  secure:
    BINSTAR_TOKEN: NuXIN9tzoKDM6kUxTBnXt2kwxFpJUFew3RiyuRAblfKkGy/oRbZGWZC5zuJREUo9kjjxjYj76YhZlM9oCc3mfWojAwsSeuB5N72BsdVBtOFnKi5W6udhvdIJw4eKUQfDOWxnvGmawSHn+LvxgoO+5sKr9dIO12nCW2z0tMBnh7h4+uAqyYMmUguqKeB3TOkGi9TI+somLYwylsxyAnwwSXtSroXkIWyGQp9bCu+ri3SvYtLyfWGb/KVGqJVNN75VMQlo9eYZ3OLfqPRuCWNSdiBk3Vu8vRnUACHbvRMLVwh9+4Asz7LL0s9yiie0W6LUm4GCTrjt6bL7hJYyGmRym5XakBk9xXQ2DwcHJA3YAPDnz0K7Uj6hLewsheJg82XRAkPcZQ7+Jna3uBeh1XEbGTb3wlpyvBFPmVHubptsR3g8XkuJbWIi1+q4wnQgHIXA5ay/ciedAPpORcqoxyna3QcU6PjLz7akvYj7xsZcbLtZyBIoWRPy3POseXI0TAPxxeps+ByKqfJIntH0RKd+NPA+O7IA5wYEOGQhi9O+sDgy8J20Y4hQwvMA4sDFO5aXJZHVUxoNrhXAvbI5U+Bax7biJ59UguB8ylyzci5by0Xct4y2kgVQXEhiiAp84/0/bvGQ+xeN8UvyzlE2o9LULhrcXFxym1mSLLXglAP7xRs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
